name: Dangboy So Ngo Nhi

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10   

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: |
          python dangboy.py   

      - name: Commit & Push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add tv.m3u full.m3u

          # chỉ commit
          git diff --cached --quiet || git commit -m "update m3u fast"

          git push
