name: LiveCDN Extractor

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Clone repository (FULL)
        run: |
          git clone --mirror https://github.com/englishcd/ai.git repo.git

      - name: Deep scan all git objects
        run: |
          mkdir -p output

          cd repo.git

          echo "EXTRACTING ALL GIT OBJECTS..."

          # ambil semua object dari seluruh history
          git rev-list --objects --all > all_objects.txt

          echo "TOTAL OBJECTS:"
          wc -l all_objects.txt

          # scan seluruh blob/object
          while read hash path; do

            git cat-file -p "$hash" 2>/dev/null | \
            grep -aoE 'https://pull\.livecdn\.cc/live/[^"'\'' <>]+' || true

          done < all_objects.txt | \
          sed 's/[",]//g' | \
          sort -u > ../output/livecdn_urls.txt

          echo ""
          echo "TOTAL URLS:"
          wc -l ../output/livecdn_urls.txt

      - name: Show sample
        run: |
          head -100 output/livecdn_urls.txt || true

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: full-history-livecdn
          path: output/livecdn_urls.txt
